title = "Extract slice data"

datapath = "../figures_sample/"
outpath = "../figures_sample/"

min = 0
max = 1
num_slices = 1

SI = false
rm_eb = false

field = "magvel"
field_list = 0

normal = "z"
location = "[0, 0, 0]"